COLOR_BACKGROUND = (123, 0, 123) # COLOR DEL FONDO 
COLOR_BLACK = (0, 0, 0) # COLOR NEGRO EN ALGUNAS VENTANAS DEL JUEGO 
COLOR_WHITE = (255, 255, 255) # COLOR BLANCO EN ALGUNAS VENTANAS DEL JUEGO 
FPS = 60.0 # VELOCIDAD DEL FOTOGRAMA POR SEGUNDO
MENU_BACKGROUND_COLOR = (228, 55, 36)
WINDOW_SIZE = (700, 700) # TAMAÑO DE LA VENTA
SQUARE_SIZE = 70 # TAMAÑO DE LOS CUADRADOS EN EL JUEGO 

